#!/usr/bin/env python3
"""
Test script to demonstrate truncation detection and handling.

This script shows how the agent detects and handles truncated LLM responses.
"""

import config

print("=" * 70)
print("Truncation Detection and Handling")
print("=" * 70)
print()

print("TOKEN LIMITS:")
print(f"  DEFAULT_MAX_TOKENS:      {config.DEFAULT_MAX_TOKENS}")
print(f"  CATEGORIZE_MAX_TOKENS:   {config.CATEGORIZE_MAX_TOKENS}")
print(f"  ANALYZE_MAX_TOKENS:      {config.ANALYZE_MAX_TOKENS}")
print(f"  VERIFY_MAX_TOKENS:       {config.VERIFY_MAX_TOKENS}")
print()

print("TRUNCATION DETECTION:")
print(f"  Warning threshold: {config.TRUNCATION_WARNING_THRESHOLD * 100:.0f}%")
print(f"  (Warns if response uses >{config.TRUNCATION_WARNING_THRESHOLD * 100:.0f}% of max_tokens)")
print()

print("=" * 70)
print("How Truncation Detection Works")
print("=" * 70)
print()

print("1. RESPONSE MONITORING:")
print("   - The OpenAI API returns a 'finish_reason' field")
print("   - finish_reason == 'length' means response was truncated")
print("   - finish_reason == 'stop' means response completed normally")
print()

print("2. AUTOMATIC WARNINGS:")
print("   When finish_reason == 'length':")
print("   [WARNING] Response was truncated due to token limit")
print("   [WARNING] This may cause JSON parsing errors")
print("   [WARNING] Increase max_tokens in config.py")
print()

print("3. NEAR-LIMIT DETECTION:")
print(f"   When response uses >{config.TRUNCATION_WARNING_THRESHOLD * 100:.0f}% of tokens:")
print("   [WARNING] Response used 15200/16000 tokens (95.0%) - may be truncated")
print()

print("4. JSON PARSING ERRORS:")
print("   If JSON parsing fails:")
print("   [ERROR] Failed to parse JSON: Unterminated string starting at...")
print("   [ERROR] Response may be truncated. Last 100 chars: ...")
print("   [ERROR] Increase ANALYZE_MAX_TOKENS in config.py (current: 16000)")
print()

print("=" * 70)
print("Example Scenarios")
print("=" * 70)
print()

print("SCENARIO 1: Response Truncated Mid-JSON")
print("-" * 70)
print()
print("LLM Response (truncated):")
print('[')
print('  {')
print('    "id": "CHANGE-1",')
print('    "type": "resource-management",')
print('    "description": "Added folio allocation in error...')
print()
print("Agent Output:")
print("[WARNING] Response was truncated due to token limit (8000 tokens)")
print("[ERROR] Failed to parse categorization JSON: Unterminated string")
print("[ERROR] Response may be truncated. Last 100 chars: ...")
print("[ERROR] Increase CATEGORIZE_MAX_TOKENS in config.py (current: 8000)")
print()

print("SCENARIO 2: Response Near Limit")
print("-" * 70)
print()
print("Response completed but used 95% of tokens:")
print("[WARNING] Response used 15200/16000 tokens (95.0%) - may be truncated")
print()

print("SCENARIO 3: Normal Completion")
print("-" * 70)
print()
print("Response completed normally at 60% of limit:")
print("[DEBUG] Finish reason: stop")
print("[DEBUG] Token usage: CompletionUsage(completion_tokens=9600, prompt_tokens=...)")
print("(No warnings)")
print()

print("=" * 70)
print("Solutions for Truncation")
print("=" * 70)
print()

print("1. INCREASE TOKEN LIMITS (config.py):")
print()
print("   For large commits:")
print("   CATEGORIZE_MAX_TOKENS = 16000")
print("   ANALYZE_MAX_TOKENS = 32000")
print("   VERIFY_MAX_TOKENS = 32000")
print()
print("   For very complex analysis:")
print("   ANALYZE_MAX_TOKENS = 64000  # Requires model with large context")
print()

print("2. USE LARGER CONTEXT MODEL:")
print()
print("   DEFAULT_MODEL = 'gpt-4-turbo'      # 128k context")
print("   DEFAULT_MODEL = 'claude-3-opus'    # 200k context")
print()

print("3. DUMP PROMPTS TO DEBUG:")
print()
print("   kernel_review_agent.py HEAD --dump-prompts")
print("   cat debug_dumps/002_response.txt  # See full truncated response")
print()

print("4. USE DEBUG MODE:")
print()
print("   kernel_review_agent.py HEAD --debug")
print("   # Shows token usage and finish reasons")
print()

print("=" * 70)
print("Token Usage by Task")
print("=" * 70)
print()

print("Typical token usage for different commits:")
print()
print("Small commit (1-2 files, simple changes):")
print(f"  Categorization:  ~1,000 tokens (limit: {config.CATEGORIZE_MAX_TOKENS})")
print(f"  Analysis:        ~3,000 tokens (limit: {config.ANALYZE_MAX_TOKENS})")
print(f"  Verification:    ~2,000 tokens (limit: {config.VERIFY_MAX_TOKENS})")
print()

print("Medium commit (3-5 files, moderate complexity):")
print(f"  Categorization:  ~3,000 tokens (limit: {config.CATEGORIZE_MAX_TOKENS})")
print(f"  Analysis:        ~8,000 tokens (limit: {config.ANALYZE_MAX_TOKENS})")
print(f"  Verification:    ~6,000 tokens (limit: {config.VERIFY_MAX_TOKENS})")
print()

print("Large commit (5+ files, complex changes):")
print(f"  Categorization:  ~6,000 tokens (limit: {config.CATEGORIZE_MAX_TOKENS})")
print(f"  Analysis:        ~15,000 tokens (limit: {config.ANALYZE_MAX_TOKENS})")
print(f"  Verification:    ~12,000 tokens (limit: {config.VERIFY_MAX_TOKENS})")
print()

print("Very large commit (10+ files, many subsystems):")
print(f"  Categorization:  ~10,000 tokens (may exceed {config.CATEGORIZE_MAX_TOKENS})")
print(f"  Analysis:        ~25,000 tokens (may exceed {config.ANALYZE_MAX_TOKENS})")
print(f"  Verification:    ~20,000 tokens (may exceed {config.VERIFY_MAX_TOKENS})")
print()
print("  → Increase token limits for very large commits!")
print()

print("=" * 70)
print("Recommended Configuration")
print("=" * 70)
print()

print("For typical kernel review:")
print("  CATEGORIZE_MAX_TOKENS = 8000    # Current default")
print("  ANALYZE_MAX_TOKENS = 16000      # Current default")
print("  VERIFY_MAX_TOKENS = 16000       # Current default")
print()

print("For large commits / complex analysis:")
print("  CATEGORIZE_MAX_TOKENS = 16000")
print("  ANALYZE_MAX_TOKENS = 32000")
print("  VERIFY_MAX_TOKENS = 32000")
print()

print("For huge commits (use with caution - expensive):")
print("  CATEGORIZE_MAX_TOKENS = 32000")
print("  ANALYZE_MAX_TOKENS = 64000")
print("  VERIFY_MAX_TOKENS = 64000")
print()

print("=" * 70)
print()
print("The agent will now warn you when responses are truncated!")
print()
