#!/usr/bin/env python3
"""
Test script to demonstrate debug output format.
This simulates what the debug output looks like without needing an LLM server.
"""

print("=== Simulated Debug Output ===\n")

print("[DEBUG] Configuration:")
print("[DEBUG]   LLM: localhost:8080")
print("[DEBUG]   Model: gpt-4")
print("[DEBUG]   Verbose: True")
print("[DEBUG]   Debug: True")
print("[DEBUG]   Dump prompts: True")
print("[DEBUG]   Dump directory: debug_dumps")
print("[DEBUG]   Output directory: .")
print()

print("Reviewing commit abc123def456...")
print("Subject: mm: fix use-after-free in page reclaim")
print()

print("[1/5] Gathering context...")
print("[DEBUG] Task 0: Context management")
print("[DEBUG] Commit SHA: abc123def456789")
print("[DEBUG] Files changed: 2")
print("[DEBUG] Diff size: 1234 chars")
print("[DEBUG] Context gathered:")
print("[DEBUG]   - Changed functions: ['shrink_page_list', 'reclaim_pages']")
print("[DEBUG]   - Files: ['mm/vmscan.c', 'mm/internal.h']")
print("[DEBUG] Subsystems matched: ['mm-reclaim.md', 'mm-vma.md']")
print()

print("[2/5] Categorizing changes...")
print("[DEBUG] Task 1: Categorizing changes")
print("[DEBUG] Calling LLM for categorization...")
print("[DEBUG] LLM call #1: model=gpt-4, max_tokens=4000, temp=0.1")
print("[DEBUG] System prompt length: 15234 chars")
print("[DEBUG] User prompt length: 2456 chars")
print("[DEBUG] Dumped prompt to: debug_dumps/001_prompt.txt")
print("[DEBUG] Response length: 567 chars")
print("[DEBUG] Dumped response to: debug_dumps/001_response.txt")
print("[DEBUG] Categories:")
print("[DEBUG]   - CHANGE-1: resource-management - Added folio allocation in e...")
print("[DEBUG]   - CHANGE-2: control-flow - Modified error handling path for ...")
print("      Found 2 change categories")
print()

print("[3/5] Analyzing for regressions...")
print("[DEBUG] Task 2: Analyzing for regressions")
print("[DEBUG] Loading subsystem guides: ['mm-reclaim.md', 'mm-vma.md']")
print("[DEBUG] Calling LLM for regression analysis...")
print("[DEBUG] LLM call #2: model=gpt-4, max_tokens=8000, temp=0.1")
print("[DEBUG] System prompt length: 28456 chars")
print("[DEBUG] User prompt length: 3123 chars")
print("[DEBUG] Dumped prompt to: debug_dumps/002_prompt.txt")
print("[DEBUG] Response length: 1234 chars")
print("[DEBUG] Token usage: CompletionUsage(completion_tokens=245, prompt_tokens=7891, total_tokens=8136)")
print("[DEBUG] Dumped response to: debug_dumps/002_response.txt")
print("[DEBUG] Findings:")
print("[DEBUG]   1. memory-leak: Can this leak the folio? The allocation is no...")
print("[DEBUG]   2. null-deref: Missing null check after allocation before use...")
print("      Found 2 potential issues")
print()

print("[4/5] Verifying findings...")
print("[DEBUG] Task 3: Verifying findings")
print("[DEBUG] Applying false-positive checks to 2 findings...")
print("[DEBUG] LLM call #3: model=gpt-4, max_tokens=8000, temp=0.1")
print("[DEBUG] System prompt length: 32123 chars")
print("[DEBUG] User prompt length: 2789 chars")
print("[DEBUG] Dumped prompt to: debug_dumps/003_prompt.txt")
print("[DEBUG] Response length: 891 chars")
print("[DEBUG] Dumped response to: debug_dumps/003_response.txt")
print("[DEBUG] Verification complete: 1 verified, 1 discarded as false positives")
print("      1 issues after verification")
print()

print("[5/5] Generating summary...")
print("[DEBUG] Task 4: Generating summary")
print("[DEBUG] Summary: This commit has a potential memory-leak that should be reviewed.")
print()

print("Review complete: 1 issue(s) found")
print()

print("Commit abc123def456: mm: fix use-after-free in page reclaim")
print("  Issues found: 1")
print("  Severity: medium")
print("  Report: review-inline-abc123def456.txt")
print("  Metadata: review-metadata-abc123def456.json")
print()

print("=== Debug Dump Files Created ===")
print("debug_dumps/001_prompt.txt    - Categorization prompt")
print("debug_dumps/001_response.txt  - Categorization response")
print("debug_dumps/002_prompt.txt    - Regression analysis prompt")
print("debug_dumps/002_response.txt  - Regression analysis response")
print("debug_dumps/003_prompt.txt    - Verification prompt")
print("debug_dumps/003_response.txt  - Verification response")
